In [1]:
import numpy as np
import scipy as sp

w = v2w * v + w0

v = inv(v2w)*(w-w0)

In [169]:
v2w=np.array([[0.02828, 0.04988, -1.19862],
             [-1.19583, -0.06351, -0.03097],
             [0.06472, -1.19519, -0.04838]]).T;
w2v=np.linalg.inv(v2w);

In [170]:
v2w

array([[ 0.02828, -1.19583,  0.06472],
       [ 0.04988, -0.06351, -1.19519],
       [-1.19862, -0.03097, -0.04838]])

In [171]:
w2v

array([[ 0.01971113,  0.03476125, -0.83238114],
       [-0.83333202, -0.04425483, -0.02150311],
       [ 0.04510422, -0.83288472, -0.03359592]])

In [172]:
v2wo=np.array([[0,0,-1],[-1,0,0],[0,-1,0]])

In [173]:
v2wo

array([[ 0,  0, -1],
       [-1,  0,  0],
       [ 0, -1,  0]])

In [174]:
np.linalg.inv(v2wo)

array([[-0., -1., -0.],
       [-0., -0., -1.],
       [-1., -0., -0.]])